# Generated by Django 5.0.4 on 2024-07-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('units_measurement', models.CharField(choices=[('Unidade', 'unid'), ('Dúzia', 'dz'), ('Quilo', 'kg'), ('Litro', 'l'), ('Peça', 'pç'), ('Pedaç', 'pdç'), ('Caixa', 'cx')], max_length=10)),
                ('purchase_price', models.FloatField(default=0.0)),
                ('sale_price', models.FloatField(default=0.0)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('stock', models.BooleanField(default=False)),
            ],
        ),
    ]
