# Generated by Django 5.0.4 on 2024-07-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtcs',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
