# Generated by Django 5.0.4 on 2024-06-10 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivedmessages',
            options={'verbose_name_plural': 'Received Messages'},
        ),
        migrations.AlterField(
            model_name='receivedmessages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 21, 35, 12, 643767)),
        ),
    ]
