# Generated by Django 5.0.4 on 2024-07-02 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_receivedmessages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedmessages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 22, 38, 10, 822781)),
        ),
    ]
