# Generated by Django 5.0.4 on 2024-07-02 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_receivedmessages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedmessages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 22, 59, 49, 177317)),
        ),
    ]
